### ISSUE TITLE
DIGITALTWIN - getting_started

### ISSUE THREAD

**Issue by despiegk** [threefoldfoundation/info_digitaltwin#1]
http://localhost:9998/wiki_twin#/getting_started

put content in how the UI will work, maybe some extra pages with mockup or so

people are very curious how it will work we need to make it tangible

goal

- let people feel the experience
- serve as some basic specs what it will be
- let it come alive

questions to answer

- how to edit office doc, in separate tab
- can code be editted
- support pdf?
- how to share files with someone (as unique link, or as drive which gets linked into our drive = like remote symlink)
    - acl?
- integration of chat/meet
- ...

**Comment by ken-de-moor** [comment]
https://github.com/threefoldfoundation/info_digitaltwin/commits/development/src/getting_started/getting_started.md

**Comment by ken-de-moor** [comment]
Getting started is implemented, other features can be ticketed and added as they actually are created. Everything that's in now is documented.
