### ISSUE TITLE
TWIN WIKI: Add information about one login / one identity

### ISSUE THREAD

**Issue by samtaggart** [threefoldfoundation/info_digitaltwin#11]
- [x] Create wiki content about the idea of one login / one identity – one set of data, ease of login, applications working for you (not the other way around), sustainability, etc.
- [x] Create any necessary links from the website to this content

**Comment by AlexandreHannelas** [comment]
Wiki content first draft done - https://secure.threefold.me/pad/#/2/pad/edit/Vr8JSbNfe5LT0uq604m9GPFC/

**Comment by samtaggart** [comment]
@AlexandreHannelas Can you please provide an update here?

**Comment by samtaggart** [comment]
@AlexandreHannelas confirmed this has been added to the wiki.
