### ISSUE TITLE
DigitalTwin Wiki - Create own DT live chat 

### ISSUE THREAD

**Issue by AlexandreHannelas** [threefoldfoundation/info_digitaltwin#12]
On a market perspective, Digital Twin is separated from Threefold 

Current Live Chat on Digital Twin wiki is the same as Threefold. It has TF logo, managed by TF Network and suggested questions & answers may not be relevant to Digital Twin. 

See picture: 
![Screen Shot 2021-04-06 at 11 36 59 AM](https://user-images.githubusercontent.com/78421574/113691391-a7582a80-96cc-11eb-9ad9-dc837e474359.png)

**Comment by sabrinasadik** [comment]
Branding it Digital Twin would make sense, but need to see if we can have the support chats in the same dashboard as the TF one - will otherwise be too much for the small support team to handle. Contacted crisp about this.

**Comment by AlexandreHannelas** [comment]
Code from @sabrinasadik:
website-id:
82cd4c77-6fec-46cc-bd86-57daff0b69e2

To be copied and added to DT Website and Wiki: 
<script type="text/javascript">window.$crisp=[];window.CRISP_WEBSITE_ID="82cd4c77-6fec-46cc-bd86-57daff0b69e2";(function(){d=document;s=d.createElement("script");s.src="https://client.crisp.chat/l.js";s.async=1;d.getElementsByTagName("head")[0].appendChild(s);})();</script>

**Comment by Vilnite** [comment]
@ehab-hassan please add live chat (code above) to DT website. Thank you :)

**Comment by ehab-hassan** [comment]
done at development branch for both

**Comment by Vilnite** [comment]
Not sure how to verify but shouldn't this be at least DT logo here instead of TF? (for both)

<img width="1315" alt="Screenshot 2021-04-14 at 17 14 53" src="https://user-images.githubusercontent.com/20182572/114725523-3b696800-9d45-11eb-8531-b3dbd4837e78.png">

<img width="1391" alt="Screenshot 2021-04-14 at 17 16 04" src="https://user-images.githubusercontent.com/20182572/114725543-3dcbc200-9d45-11eb-9bb3-a29965a21006.png">

**Comment by sabrinasadik** [comment]
![photo_2021-04-13 17 51 02](https://user-images.githubusercontent.com/31733464/114733873-ff81d300-9d43-11eb-9fd1-88eaed5381e7.jpeg)
Website & domain correct @xmonader ?

**Comment by sabrinasadik** [comment]
<img width="858" alt="Screenshot 2021-04-14 at 17 07 06" src="https://user-imag@xmonader ? s.githubusercontent.com/31733464/114734119-39eb7000-9d44-11eb-992f-770dc147ec5d.png">
Website & domain correct @xmonader ?

**Comment by sabrinasadik** [comment]
Website & domain correct? @xmonader 
<img width="880" alt="Screenshot 2021-04-14 at 17 11 04" src="https://user-images.githubusercontent.com/31733464/114734380-71f2b300-9d44-11eb-9e4d-81169a1d71b2.png">

**Comment by sabrinasadik** [comment]
<img width="457" alt="Screenshot 2021-04-14 at 17 37 17" src="https://user-images.githubusercontent.com/31733464/114738416-3ce85f80-9d48-11eb-9d0d-38f730e64cc9.png">

**Comment by sabrinasadik** [comment]
Seems to work now

**Comment by Vilnite** [comment]
Works on website, still TF on wiki:

![Uploading Screenshot 2021-04-15 at 11.00.36.png…]()

**Comment by sabrinasadik** [comment]
Wiki setup instructions:

Website ID: 
fa9a7744-5454-4e83-99ae-9ef342d3bff4

Code:
<script type="text/javascript">window.$crisp=[];window.CRISP_WEBSITE_ID="fa9a7744-5454-4e83-99ae-9ef342d3bff4";(function(){d=document;s=d.createElement("script");s.src="https://client.crisp.chat/l.js";s.async=1;d.getElementsByTagName("head")[0].appendChild(s);})();</script>

**Comment by ehab-hassan** [comment]
![image](https://user-images.githubusercontent.com/10484295/114854641-555a8780-9de5-11eb-89f6-0ed1f25f45f9.png)
I updated script with new id at wikis but it keep show the old at local @Hamdy can u check please

**Comment by Hamdy** [comment]
done
